/** Services.Packages.Package DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaGetByApKe"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaGetByApKePaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaGetByApKeCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaGetByOw"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaGetByOwPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaGetByOwCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNaFoApKe"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNaFoApKePaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNaFoApKeCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.LocalPackage DROP Relation SPs **/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LoPaSeByPaNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LoPaSeByPaNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LoPaSeByPaNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


/** Services.Packages.ApiKey DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeGetByCu"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeGetByCuPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeGetByCuCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeGetByOw"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeGetByOwPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeGetByOwCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoIn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoInPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoInCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoInOnCu"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoInOnCuPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoInOnCuCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Log.ApplicationException DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByApKe"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByApKePaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByApKeCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByPaEx"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByPaExPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByPaExCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByOw"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByOwPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExGetByOwCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaOnApKe"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaOnApKePaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaOnApKeCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSoOnApKe"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSoOnApKePaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSoOnApKeCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Customer DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuGetByPa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuGetByPaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuGetByPaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuGetByOw"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuGetByOwPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuGetByOwCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaPa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaPaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaPaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaOnPa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaOnPaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaOnPaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaOnPa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaOnPaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaOnPaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.CustomerUserEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByUsLo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByUsLoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByUsLoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByCu"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByCuPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByCuCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByOw"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByOwPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnGetByOwCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



/** Services.Packages.Purchase DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByApKe"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByApKePaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByApKeCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByCl"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByClPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByClCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByOw"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByOwPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGetByOwCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGeAl"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGeAlPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGeAlCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


/** Services.Packages.PurchaseLine DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiGetByPuOr"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiGetByPuOrPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiGetByPuOrCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiGetByOw"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiGetByOwPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiGetByOwCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



/** Services.Packages.Security.ModelUser DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsGetByOw"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsGetByOwPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsGetByOwCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByEm"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByEmPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByEmCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeEnByNaAnEm"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeEnByNaAnEmPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeEnByNaAnEmCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


/** Services.Packages.Security.ModelSession DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoSeGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoSeGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoSeGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



/** Services.Packages.Security.ModelUserRights DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNaAnUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNaAnUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNaAnUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.Securable DROP Relation SPs **/



/** Services.Packages.Security.IPRegistered DROP Relation SPs **/



/** Services.Packages.Security.IPSessionRegistration DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSeReGetByIP"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSeReGetByIPPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSeReGetByIPCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSeReGetBySe"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSeReGetBySePaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSeReGetBySeCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



/** Services.Packages.Security.PackageAccessControlList DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGetByPa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGetByPaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGetByPaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGeACLs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGeACLsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoLiGeACLsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PackageAccessControlEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoEnGetByACL"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoEnGetByACLPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoEnGetByACLCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoEnGeEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoEnGeEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaAcCoEnGeEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.ApiKeyAccessControlList DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGetByApKe"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGetByApKePaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGetByApKeCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGeACLs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGeACLsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoLiGeACLsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.ApiKeyAccessControlEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoEnGetByACL"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoEnGetByACLPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoEnGetByACLCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoEnGeEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoEnGeEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeAcCoEnGeEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Log.Security.ApplicationExceptionAccessControlList DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGetByApEx"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGetByApExPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGetByApExCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGeACLs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGeACLsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoLiGeACLsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Log.Security.ApplicationExceptionAccessControlEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoEnGetByACL"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoEnGetByACLPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoEnGetByACLCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoEnGeEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoEnGeEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExAcCoEnGeEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.CustomerAccessControlList DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGetByCu"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGetByCuPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGetByCuCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGeACLs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGeACLsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoLiGeACLsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.CustomerAccessControlEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoEnGetByACL"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoEnGetByACLPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoEnGetByACLCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoEnGeEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoEnGeEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuAcCoEnGeEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.CustomerUserEntryAccessControlList DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGetByCuUsEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGetByCuUsEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGetByCuUsEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGeACLs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGeACLsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoLiGeACLsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.CustomerUserEntryAccessControlEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoEnGetByACL"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoEnGetByACLPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoEnGetByACLCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoEnGeEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoEnGeEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUsEnAcCoEnGeEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PurchaseAccessControlList DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGetByPu"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGetByPuPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGetByPuCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGeACLs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGeACLsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoLiGeACLsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PurchaseAccessControlEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoEnGetByACL"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoEnGetByACLPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoEnGetByACLCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoEnGeEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoEnGeEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuAcCoEnGeEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PurchaseLineAccessControlList DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGetByPuLi"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGetByPuLiPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGetByPuLiCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGeACLs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGeACLsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoLiGeACLsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PurchaseLineAccessControlEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoEnGetByACL"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoEnGetByACLPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoEnGetByACLCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoEnGeEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoEnGeEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiAcCoEnGeEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.Security.ModelUserAccessControlList DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGetByUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGetByUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGetByUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGetByMoUs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGetByMoUsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGetByMoUsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGeACLs"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGeACLsPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoLiGeACLsCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.Security.ModelUserAccessControlEntry DROP Relation SPs **/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoEnGetByACL"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoEnGetByACLPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoEnGetByACLCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/



BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoEnGeEn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoEnGeEnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsAcCoEnGeEnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Platform.Module.UndoRedo.Services.Packages.UndoRedoOptions DROP Relation SPs **/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReOpSeByEnTy"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReOpSeByEnTyPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReOpSeByEnTyCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


/** Platform.Module.UndoRedo.Services.Packages.UndoRedoGroup DROP Relation SPs **/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReGrSeByEnTy"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReGrSeByEnTyPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReGrSeByEnTyCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


/** Services.Packages.CustomerUndoRedo DROP Relation SPs **/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnOpOr"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnOpOrPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnOpOrCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiOpSo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiOpSoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiOpSoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFi"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


/** Services.Packages.PurchaseUndoRedo DROP Relation SPs **/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnOpOr"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnOpOrPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnOpOrCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiOpSo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiOpSoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiOpSoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFi"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


/** Services.Packages.PurchaseLineUndoRedo DROP Relation SPs **/


BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnOpOr"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnOpOrPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnOpOrCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiOpSo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiOpSoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiOpSoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFi"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/


/** Services.Packages.Package DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PaSeByPaNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.LocalPackage DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LocalPackageCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LocalPackageDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LocalPackageRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LocalPackageUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LoPaSeByPaNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LoPaSeByPaNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "LoPaSeByPaNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.ApiKey DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoIn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoInPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApKeSeByCoInCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Log.ApplicationException DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApExSeByNaSoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Customer DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaPa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaPaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuSeByNaAnPaPaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.CustomerUserEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Purchase DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGeAl"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGeAlPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuGeAlCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.PurchaseLine DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.ModelUser DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByEm"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByEmPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeByEmCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeEnByNaAnEm"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeEnByNaAnEmPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsSeEnByNaAnEmCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.ModelSession DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelSessionCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelSessionDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelSessionRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelSessionUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.ModelUserRights DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserRightsCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserRightsDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserRightsRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserRightsUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNa"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNaPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "MoUsRiGeByNaCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.Securable DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "SecurableCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "SecurableDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "SecurableRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "SecurableUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.IPRegistered DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPRegisteredCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPRegisteredDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPRegisteredRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPRegisteredUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.IPSessionRegistration DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSessionRegistrationCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSessionRegistrationDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSessionRegistrationRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "IPSessionRegistrationUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PackageAccessControlList DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageAccessControlListCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageAccessControlListDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageAccessControlListRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageAccessControlListUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PackageAccessControlEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageAccessControlEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageAccessControlEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageAccessControlEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PackageAccessControlEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.ApiKeyAccessControlList DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyAccessControlListCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyAccessControlListDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyAccessControlListRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyAccessControlListUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.ApiKeyAccessControlEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyAccessControlEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyAccessControlEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyAccessControlEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApiKeyAccessControlEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Log.Security.ApplicationExceptionAccessControlList DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionAccessControlListCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionAccessControlListDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionAccessControlListRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionAccessControlListUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Log.Security.ApplicationExceptionAccessControlEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionAccessControlEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionAccessControlEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionAccessControlEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ApplicationExceptionAccessControlEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.CustomerAccessControlList DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerAccessControlListCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerAccessControlListDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerAccessControlListRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerAccessControlListUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.CustomerAccessControlEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerAccessControlEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerAccessControlEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerAccessControlEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerAccessControlEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.CustomerUserEntryAccessControlList DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryAccessControlListCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryAccessControlListDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryAccessControlListRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryAccessControlListUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.CustomerUserEntryAccessControlEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryAccessControlEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryAccessControlEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryAccessControlEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUserEntryAccessControlEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PurchaseAccessControlList DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseAccessControlListCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseAccessControlListDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseAccessControlListRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseAccessControlListUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PurchaseAccessControlEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseAccessControlEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseAccessControlEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseAccessControlEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseAccessControlEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PurchaseLineAccessControlList DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineAccessControlListCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineAccessControlListDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineAccessControlListRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineAccessControlListUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.PurchaseLineAccessControlEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineAccessControlEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineAccessControlEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineAccessControlEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineAccessControlEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.Security.ModelUserAccessControlList DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserAccessControlListCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserAccessControlListDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserAccessControlListRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserAccessControlListUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.Security.Security.ModelUserAccessControlEntry DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserAccessControlEntryCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserAccessControlEntryDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserAccessControlEntryRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "ModelUserAccessControlEntryUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Platform.Module.UndoRedo.Services.Packages.UndoRedoOptions DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UndoRedoOptionsCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UndoRedoOptionsDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UndoRedoOptionsRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UndoRedoOptionsUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReOpSeByEnTy"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReOpSeByEnTyPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReOpSeByEnTyCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Platform.Module.UndoRedo.Services.Packages.UndoRedoGroup DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UndoRedoGroupCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UndoRedoGroupDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UndoRedoGroupRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UndoRedoGroupUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReGrSeByEnTy"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReGrSeByEnTyPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "UnReGrSeByEnTyCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.CustomerUndoRedo DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUndoRedoCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUndoRedoDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUndoRedoRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CustomerUndoRedoUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnOpOr"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnOpOrPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlFiByIsUnOpOrCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiOpSo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiOpSoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiOpSoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFi"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "CuUnReGeAlWiNoFiCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.PurchaseUndoRedo DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseUndoRedoCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseUndoRedoDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseUndoRedoRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseUndoRedoUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnOpOr"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnOpOrPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlFiByIsUnOpOrCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiOpSo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiOpSoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiOpSoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFi"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuUnReGeAlWiNoFiCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

/** Services.Packages.PurchaseLineUndoRedo DROP CRUD sp's **/
BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineUndoRedoCreate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineUndoRedoDelete"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineUndoRedoRead"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PurchaseLineUndoRedoUpdate"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUn"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnOpOr"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnOpOrPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlFiByIsUnOpOrCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiOpSo"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiOpSoPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiOpSoCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFi"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiPaged"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP PROCEDURE "PuLiUnReGeAlWiNoFiCount"';
	EXCEPTION WHEN OTHERS THEN null;
END;
/

